Fix crash in lexer around tNL tokens (#10207)
* Add failing test

Wanted to make sure that it crashes even with the `# error` comments and
`# typed:` sigil. The minimal test is just

    def
      ensure

* Admit defeat

I thought for a while about how to fix this in a better way. The root
failure is that we hit an assertion in `compare_indent_level` that says
"it only makes sense to compare the indentation level of two tokens if
they're not `tNL` tokens." Adding this guard here basicaly weakens that
assertion.

It would have been better if we could have figured out how to get the
`bodyStartToken` to not be `tNL`, but I'm sort of coming to the
conclusion that due to empty production rules, it could kind of sneak in
from anywhere. If the grammar decides to make an empty production, bison
will use whatever the most recently lexed token was for the empty stmts'
`@$` loc. We _could_ change the default, so that they're initialized as
`nullptr` in that case possibly? But I think to do that we would have to
write code in every empty production rule (possibly, didn't think too
hard about that).

In any case, I think it's probably just safer to be defensive,
especially if we're hoping that this code doesn't live very long. I've
already verified that Prism is able to recover well enough on this
input, so we should just not crash.

* Ignore this test

Prism thinks this is a method `def ensure` with an empty body.

Sorbet thinks this is a method `def <method-def-name-missing>` with a
body containing `<ErrorNode>`.

    test/pipeline_test_runner.cc:321: ERROR: Prism desugared tree does not match legacy desugared tree
    @@ -12,7 +12,7 @@
         MethodDef{
           loc = 2:3-6:1
           flags = {}
    -      name = <U <method-def-name-missing>><<U <todo method>>>
    +      name = <U ensure><<U <todo method>>>
           args = [BlockParam{ loc = , expr = UnresolvedIdent{
               loc =
               kind = Local
    @@ -19,13 +19,10 @@
               name = <U <blk>>
             } }]
    -      rhs = Rescue{
    -        loc = 5:3-5:9
    -        body = EmptyTree
    -        rescueCases = [
    -        ]
    -        else = EmptyTree
    -        ensure = EmptyTree
    +      rhs = ConstantLit{
    +        loc = 182-205
    +        symbol = (static-field ::<ErrorNode>)
    +        orig = nullptr
           }
         }
       ]
     }