Fix `Bad resolutionScopes` crash (#10445)
* Add some old tests from #6253

Not sure whether these are redundant with tests that were added in the
mean time, but I figured I would add them anyways, because this PR is
changing similar things.

* Add test that shows the `resolutionScopes` crash

The full backtrace from the crash:

    [2026-07-09 21:04:40.688] [fatalFallback] [error] Exception::raise() msg="ast/Trees.cc:356 enforced condition nested->symbol() == core::Symbols::StubModule() has failed: (no message provided)"

    [2026-07-09 21:04:40.890] [fatalFallback] [error] Backtrace:
      #3 0xc50647c3c52c sorbet::test::Expectations::Expectations()
      #4 0xc506486d7178 sorbet::ast::ConstantLit::fullUnresolvedPath()
      #5 0xc506485fecb4 sorbet::resolver::(anonymous namespace)::getResultTypeAndBindWithSelfTypeParamsImpl()
      #6 0xc506485fdc60 sorbet::resolver::(anonymous namespace)::getResultTypeAndBindWithSelfTypeParams()
      #7 0xc506485fcb54 sorbet::resolver::(anonymous namespace)::getResultTypeWithSelfTypeParams()
      #8 0xc506485fc3c0 sorbet::resolver::(anonymous namespace)::parseSigWithSelfTypeParams()
      #9 0xc506485f8ff0 sorbet::resolver::TypeSyntax::parseSig()
      #10 0xc506485f8f38 sorbet::resolver::TypeSyntax::parseSigTop()
      #11 0xc5064842c0d8 sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::parseSig()
      #12 0xc5064842bb78 sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::processStatement()::{lambda()#1}::operator()()
      #13 0xc5064842b30c sorbet::typecaseHelper<>()
      #14 0xc5064842b1a0 sorbet::typecase<>()
      #15 0xc5064842aed4 sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::processStatement()
      #16 0xc5064842ad9c sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::processClassBody()
      #17 0xc5064842acfc sorbet::resolver::(anonymous namespace)::ResolveSignaturesWalk::postTransformClassDef()
      #18 0xc5064842ac80 sorbet::ast::MapFunctions<>::CALL_MEMBER_impl_postTransformClassDef<>::call<>()
      #19 0xc5064842a074 sorbet::ast::TreeMapper<>::mapClassDef()
      #20 0xc506484296d8 sorbet::ast::TreeMapper<>::mapIt()
      #21 0xc5064842a03c sorbet::ast::TreeMapper<>::mapClassDef()
      #22 0xc506484296d8 sorbet::ast::TreeMapper<>::mapIt()
      #23 0xc50648428e28 sorbet::ast::ShallowWalk::apply<>()
      #24 0xc50648428c2c sorbet::resolver::(anonymous namespace)::resolveSigs()::$_0::operator()()
      #25 0xc50648428b28 std::__1::__invoke[abi:v15007]<>()
      #26 0xc50648428ae0 std::__1::__invoke_void_return_wrapper<>::__call<>()
      #27 0xc50648428abc std::__1::__function::__alloc_func<>::operator()[abi:v15007]()
      #28 0xc50648427d1c std::__1::__function::__func<>::operator()()
      #29 0xc50648566a8c std::__1::__function::__value_func<>::operator()[abi:v15007]()
      #30 0xc5064855abac std::__1::function<>::operator()()
      #31 0xc506489817ac sorbet::WorkerPoolImpl::multiplexJob()
      #32 0xc5064838c524 sorbet::resolver::(anonymous namespace)::resolveSigs()
      #33 0xc5064838d040 sorbet::resolver::Resolver::runIncremental()
      #34 0xc5064806196c sorbet::realmain::pipeline::incrementalResolve()
      #35 0xc50647d77ddc sorbet::realmain::lsp::LSPTypechecker::runFastPath()
      #36 0xc50647d761ec sorbet::realmain::lsp::LSPTypechecker::typecheck()
      #37 0xc50647d7ac48 sorbet::realmain::lsp::LSPTypecheckerDelegate::typecheckOnFastPath()
      #38 0xc50647dead84 sorbet::realmain::lsp::SorbetWorkspaceEditTask::run()
      #39 0xc50647f19ce8 sorbet::realmain::lsp::(anonymous namespace)::TypecheckerTask::run()
      #40 0xc50647f18424 sorbet::realmain::lsp::LSPTypecheckerCoordinator::asyncRunInternal()
      #41 0xc50647f184c4 sorbet::realmain::lsp::LSPTypecheckerCoordinator::syncRun()
      #42 0xc50647f0e214 sorbet::realmain::lsp::LSPLoop::runTask()
      #43 0xc50647f0de4c sorbet::realmain::lsp::LSPLoop::processRequests()
      #44 0xc50647f02664 sorbet::realmain::lsp::SingleThreadedLSPWrapper::getLSPResponsesFor()
      #45 0xc50647c60af0 sorbet::test::getLSPResponsesFor()
      #46 0xc50647ad83b4 sorbet::test::DOCTEST_ANON_FUNC_52()
      #47 0xc50648a8c148 doctest::Context::run()
      #48 0xc50647ad9334 main
      #49 0xfc4ea21584c4
      #50 0xfc4ea2158598 __libc_start_main
      #51 0xc50647acdb70 _start

* Don't dealias in constantResolutionFailed

If we see an example like

    A = B
    A::X

We need to say that the `resolutionScopes` for `A::X` is `[A]`.
Previously, the `dealias` here caused us to say that the scope was
`[noSymbol()]` for `X`, which is wrong--we would have looked for `X` in
`A` if we had known what `A` was an alias to.

If we do know what `A` is an alias to, it's still fine to say that the
resolution scope was `A`--we can always dealias it downstream if need be.

Reapplies eb078dcdbf457f71b3e636fcaaef011c13fa652d , from this PR:

<https://github.com/sorbet/sorbet/pull/6253/changes/eb078dcdbf457f71b3e636fcaaef011c13fa652d>

* Show that this test changes

This is actually good behavior, because it makes it more obvious in the
`resolutionScopes` that we were attempting to resolve the constant on
`AliasToA`, not on `A` directly. Recall that the test case looks like
this:

    sig {returns(AliasToA::B)}
    #            ^^^^^^^^^^^ error: Unable to resolve constant `B`
    def example; end

* wip: Attempt to add the package-directed test case

    + exec test/lsp_test_runner --single_test test/testdata/packager/bad_full_unresolved_path
    Pausing
    [doctest] doctest version is "2.4.9"
    [doctest] run with "--help" for options
    [2026-07-09 21:45:13.597] [fatalFallback] [error] Exception::raise() msg="main/pipeline/pipeline.cc:866 enforced condition !traversal.strata.empty() has failed: (no message provided)"

    [2026-07-09 21:45:13.727] [fatalFallback] [error] Backtrace:
      #3 0xb44ef313c52c sorbet::test::Expectations::Expectations()
      #4 0xb44ef355f204 sorbet::realmain::pipeline::computePackageStrata()
      #5 0xb44ef32804c0 sorbet::realmain::lsp::LSPTypechecker::runSlowPath()::$_2::operator()()
      #6 0xb44ef327f978 std::__1::__invoke[abi:v15007]<>()
      #7 0xb44ef327f928 std::__1::__invoke_void_return_wrapper<>::__call<>()
      #8 0xb44ef327f8fc std::__1::__function::__alloc_func<>::operator()[abi:v15007]()
      #9 0xb44ef327ed0c std::__1::__function::__func<>::operator()()
      #10 0xb44ef3d42a70 std::__1::__function::__value_func<>::operator()[abi:v15007]()
      #11 0xb44ef3d42958 std::__1::function<>::operator()()
      #12 0xb44ef3d42490 sorbet::core::lsp::TypecheckEpochManager::tryCommitEpoch()
      #13 0xb44ef3275844 sorbet::realmain::lsp::LSPTypechecker::runSlowPath()
      #14 0xb44ef3274e08 sorbet::realmain::lsp::LSPTypechecker::initialize()
      #15 0xb44ef327aa64 sorbet::realmain::lsp::LSPTypecheckerDelegate::initialize()
      #16 0xb44ef32fcb4c sorbet::realmain::lsp::InitializedTask::run()
      #17 0xb44ef3419ce8 sorbet::realmain::lsp::(anonymous namespace)::TypecheckerTask::run()
      #18 0xb44ef3418424 sorbet::realmain::lsp::LSPTypecheckerCoordinator::asyncRunInternal()
      #19 0xb44ef34184c4 sorbet::realmain::lsp::LSPTypecheckerCoordinator::syncRun()
      #20 0xb44ef340e310 sorbet::realmain::lsp::LSPLoop::runTask()
      #21 0xb44ef340de4c sorbet::realmain::lsp::LSPLoop::processRequests()
      #22 0xb44ef3402664 sorbet::realmain::lsp::SingleThreadedLSPWrapper::getLSPResponsesFor()
      #23 0xb44ef3160af0 sorbet::test::getLSPResponsesFor()
      #24 0xb44ef315edd8 sorbet::test::getLSPResponsesFor()
      #25 0xb44ef31603f4 sorbet::test::initializeLSP()
      #26 0xb44ef2fd4f80 sorbet::test::DOCTEST_ANON_FUNC_52()
      #27 0xb44ef3f8c128 doctest::Context::run()
      #28 0xb44ef2fd9334 main
      #29 0xf1f41dea84c4
      #30 0xf1f41dea8598 __libc_start_main
      #31 0xb44ef2fcdb70 _start

    ===============================================================================
    test/lsp_test_runner.cc:483:
    TEST CASE:  LSPTest

    test/lsp_test_runner.cc:483: ERROR: test case THREW exception: main/pipeline/pipeline.cc:866 enforced condition !traversal.strata.empty() has failed: (no message provided)

* Needs to start with `directed` to opt out of LSP tests