Squashed commit of the following:
commit 47272bf594cfbfe604e359e8958084c5c64a82da
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Wed Jul 29 13:14:14 2026 -0700

    Fix bug with `__callee__` in `BasicObject` subclasses

    Previously this would fail like this:

          1) Error:
        Opus::Types::Test::EdgeCasesTest#test_0031_works with BasicObject subclass (no Kernel#__callee__):
        NameError: undefined local variable or method '__callee__' for an instance of #<Class:0x0000ebdb18d09078>
            lib/types/private/methods/_methods.rb:387:in 'block in _on_method_added'
            test/types/edge_cases.rb:1145:in 'block in <class:EdgeCasesTest>'

    Stripe's codebase has a test that looks like this.

commit 1cb3b3007a37d8173b261d56dc94ef1060966c01
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Wed Jul 29 11:43:16 2026 -0700

    bex rubocop -a test/types/edge_cases.rb

commit 79463abaad2ff6d1c926d68e9c78ff50bfb94049
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Wed Jul 29 10:48:56 2026 -0700

    Fix alias_method allocating on every call when sig is cached

    When `built_sig` is set (from a prior call to foo), a call through
    bar skips the `if !method_sig` block entirely, so `_unwrap_alias`
    inside that block would never fire. The alias stays permanently wrapped,
    allocating on every call.

    Moving the `_unwrap_alias` call outside the sig-resolution block makes
    it runs regardless of whether `built_sig` was already cached.

    Fixes the allocations tests.

commit ef67d6fc1e2c3ccd358ea168db62f4a7d5a1a70c
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Thu Jun 25 18:15:43 2026 -0700

    Also store the Signature in the closure

    This fixes the `module_function` tests, which is unfortunate.

commit a90df020ca4d9a0b0766af2c0c62576b42d0f0ac
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Wed Jun 24 20:54:28 2026 -0700

    Make sorbet-runtime tolerant of method redefinitions

    Some tests get better, but some tests get worse, specifically the
    allocation tests and two tests that start failing for RuntimeError.

commit 77c071f6551c0fc3a562c3f6a228d6f53a74b227
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Wed Jul 29 11:14:32 2026 -0700

    Make the tests pass artificially, to show current behavior

commit 68e39e7bf0da7497e1a0dd85505ce0b6bc3bd03f
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Wed Jun 24 20:50:31 2026 -0700

    Add failing tests

    The failures:

          1) Failure:
        Opus::Types::Test::EdgeCasesTest::aliasing::singleton method#test_0004_handles alias without runtime checking [test/types/edge_cases.rb:382]:
        Expected: 0
          Actual: 1

          2) Failure:
        Opus::Types::Test::EdgeCasesTest::aliasing::singleton method#test_0002_handles alias_method without runtime checking [test/types/edge_cases.rb:334]:
        Expected: 0
          Actual: 1

          3) Failure:
        Opus::Types::Test::EdgeCasesTest#test_0026_drops an un-evaluated sig if the method is redefined [test/types/edge_cases.rb:1027]:
        Expected #<T::Private::Methods::Signature:0x0000f9f86059c308 @method=#<UnboundMethod: #<Class:0x0000f9f862c2b190>#foo() /pay/home/jez/sorbet/gems/sorbet-runtime/test/types/edge_cases.rb:1021>, @method_name=:foo, @block_type=nil, @block_name=nil, @rest_type=nil, @rest_name=nil, @keyrest_type=nil, @keyrest_name=nil, @return_type=#<T::Types::Simple:0x0000f9f8633504e8 @raw_type=Integer, @name="Integer", @nilable=#<T::Private::Types::SimplePairUnion:0x0000f9f86337f978 @raw_a=Integer, @raw_b=NilClass, @types=[#<T::Types::Simple:0x0000f9f8633504e8 ...>, #<T::Types::Simple:0x0000f9f863090230 @raw_type=NilClass, @name="NilClass">]>>, @effective_return_type=#<T::Types::Simple:0x0000f9f8633504e8 @raw_type=Integer, @name="Integer", @nilable=#<T::Private::Types::SimplePairUnion:0x0000f9f86337f978 @raw_a=Integer, @raw_b=NilClass, @types=[#<T::Types::Simple:0x0000f9f8633504e8 ...>, #<T::Types::Simple:0x0000f9f863090230 @raw_type=NilClass, @name="NilClass">]>>, @bind=nil, @mode="standard", @check_level=:always, @parameters=[], @on_failure=nil, @override_allow_incompatible=false, @defined_raw=nil, @arg_types=[], @kwarg_types={}, @req_arg_count=0, @req_kwarg_names=[]> to be nil.

          4) Failure:
        Opus::Types::Test::EdgeCasesTest#test_0036_handles define_method redefinition: call via original UnboundMethod [test/types/edge_cases.rb:1255]:
        Expected: [:patch, :unpatch]
          Actual: [:unpatch]

          5) Failure:
        Opus::Types::Test::EdgeCasesTest#test_0032_handles alias_method + redefinition: call patched first [test/types/edge_cases.rb:1157]:
        Expected: [:patch, :unpatch]
          Actual: [:unpatch]

          6) Failure:
        Opus::Types::Test::EdgeCasesTest#test_0028_preserves define_method wrapper when sig is evaluated via bind_call [test/types/edge_cases.rb:1080]:
        Expected: "wrapped(original)"
          Actual: "original"

          7) Failure:
        Opus::Types::Test::EdgeCasesTest#test_0034_handles alias_method + redefinition that calls old method [test/types/edge_cases.rb:1204]:
        Expected: [:patch, :unpatch]
          Actual: [:unpatch]

          8) Error:
        Opus::Types::Test::EdgeCasesTest#test_0030_does not validate module_function singleton call against a redefined sig:
        TypeError: Parameter 'x': Expected type String, got type Integer with value 42
        Caller: /pay/home/jez/sorbet/gems/sorbet-runtime/test/types/edge_cases.rb:1126
        Definition: /pay/home/jez/sorbet/gems/sorbet-runtime/test/types/edge_cases.rb:1116 (#<Module:0x0000f9f860357e58>#foo)
            lib/types/configuration.rb:261:in 'T::Configuration.call_validation_error_handler_default'
            lib/types/configuration.rb:268:in 'T::Configuration.call_validation_error_handler'
            lib/types/private/methods/call_validation.rb:381:in 'T::Private::Methods::CallValidation.report_error'
            lib/types/private/methods/call_validation.rb:279:in 'block in T::Private::Methods::CallValidation.validate_call'
            lib/types/private/methods/signature.rb:224:in 'T::Private::Methods::Signature#each_args_value_type'
            lib/types/private/methods/call_validation.rb:276:in 'T::Private::Methods::CallValidation.validate_call'
            lib/types/private/methods/_methods.rb:379:in 'block in _on_method_added'
            test/types/edge_cases.rb:1126:in 'block in <class:EdgeCasesTest>'

          9) Error:
        Opus::Types::Test::EdgeCasesTest#test_0027_does not validate a captured old method against a new sig:
        TypeError: Return value: Expected type Float, got type Integer with value 0
        Caller: /pay/home/jez/sorbet/gems/sorbet-runtime/test/types/edge_cases.rb:1057
        Definition: /pay/home/jez/sorbet/gems/sorbet-runtime/test/types/edge_cases.rb:1043 (#<Class:0x0000f9f860352b38>.foo)
            lib/types/configuration.rb:261:in 'T::Configuration.call_validation_error_handler_default'
            lib/types/configuration.rb:268:in 'T::Configuration.call_validation_error_handler'
            lib/types/private/methods/call_validation.rb:381:in 'T::Private::Methods::CallValidation.report_error'
            lib/types/private/methods/call_validation.rb:340:in 'T::Private::Methods::CallValidation.validate_call'
            lib/types/private/methods/_methods.rb:379:in 'block in _on_method_added'
            test/types/edge_cases.rb:1057:in 'Method#call'
            test/types/edge_cases.rb:1057:in 'block in <class:EdgeCasesTest>'