Use Apple's linker for macOS builds
There were failures on the macOS test sanitizer job, because there seems
to be some sort of bug in exception handling when sanitizers are turned
on:

- https://github.com/llvm/llvm-project/issues/224309
- https://buildkite.com/sorbet/sorbet/builds/44757#01a11583-94bd-4507-a06c-3a76afc4a1a3

The errors looked like this:

    [fatalFallback] [error] Sorbet raised uncaught exception type="sorbet::FileNotFoundException" what="Couldn't open directory `common_test_missing_dir`"
    __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) (in libc++abi.dylib) + 0
    common/test/common_test.cc:35: FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal

in tests that were expecting to catch those raised exceptions.

The issue mentions that this doesn't affect Apple's linker, only the one
distributed via LLVM. Hopefully they'll fix that, and then we can go
back to using the bundled linker, but for now, there is a setting in the
toolchain we can use which will let us fall back to the Apple linker.