Failing test: preemption in package-directed mode
The package-directed version of the test fails because there is a
diagnostic reported, which is not reported for the monolithic version:

    test/lsp/multithreaded_protocol_test_corpus.cc:1689:
    TEST CASE:  PackageDirectedPreemptionWithTestExports

    test/lsp/multithreaded_protocol_test_corpus.cc:172: ERROR: Expected fast path status, but received diagnostics:
    {
        "jsonrpc": "2.0",
        "method": "textDocument/publishDiagnostics",
        "params": {
            "uri": "file:///Users/jvilk/stripe/pay-server/__package.rb",
            "diagnostics": [
                {
                    "range": {
                        "start": {
                            "line": 4,
                            "character": 9
                        },
                        "end": {
                            "line": 4,
                            "character": 13
                        }
                    },
                    "severity": 1,
                    "code": 5002,
                    "codeDescription": {
                        "href": "https://srb.help/5002"
                    },
                    "source": "Sorbet",
                    "message": "Unable to resolve constant `Test` (fix available)",
                    "relatedInformation": [
                        {
                            "location": {
                                "uri": "file:///Users/jvilk/stripe/pay-server/__package.rb",
                                "range": {
                                    "start": {
                                        "line": 4,
                                        "character": 9
                                    },
                                    "end": {
                                        "line": 4,
                                        "character": 13
                                    }
                                }
                            },
                            "message": "Did you mean `Root`? (fix available)"
                        },
                        {
                            "location": {
                                "uri": "file:///Users/jvilk/stripe/pay-server/__package.rb",
                                "range": {
                                    "start": {
                                        "line": 2,
                                        "character": 0
                                    },
                                    "end": {
                                        "line": 2,
                                        "character": 24
                                    }
                                }
                            },
                            "message": "`Root` defined here"
                        }
                    ]
                }
            ]
        }
    }