Fix issue with forward declares/incomplete types in cache
This is the issue I was seeing:

      (cd /private/var/tmp/_bazel/491a13d243378e23690a7f8390a5c09f/sandbox/darwin-sandbox/590/execroot/com_stripe_ruby_typer && \
      exec env - \
        EMCC_WASM_BACKEND=1 \
        EM_BIN_PATH=external/emscripten_bin_mac \
        EM_CONFIG_PATH=external/emsdk/emscripten_toolchain/emscripten_config \
        PATH=/bin:/usr/bin:/usr/local/bin \
        PWD=/proc/self/cwd \
        TMPDIR=/var/folders/tv/zxkj31vd52n40j8fyt91vtj40000gn/T/ \
      /usr/bin/sandbox-exec -f /private/var/tmp/_bazel/491a13d243378e23690a7f8390a5c09f/sandbox/darwin-sandbox/590/sandbox.sb /private/var/tmp/_bazel/install/22a33b4bcd3e158cee3fae2c530b47de/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel/491a13d243378e23690a7f8390a5c09f/sandbox/darwin-sandbox/590/stats.out' external/emsdk/emscripten_toolchain/emcc.sh @bazel-out/wasm-fastbuild-ST-b4dbd4a2bfc4/bin/main/cache/_objs/cache/cache-orig.o.params)
    In file included from main/cache/cache-orig.cc:1:
    In file included from ./main/cache/cache.h:4:
    In file included from external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/memory:939:
    In file included from external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/__memory/shared_ptr.h:33:
    external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/__memory/unique_ptr.h:64:19: error: invalid application of 'sizeof' to an incomplete type 'sorbet::KeyValueStore'
       64 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
          |                   ^~~~~~~~~~~
    external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/__memory/unique_ptr.h:266:7: note: in instantiation of member function 'std::default_delete<sorbet::KeyValueStore>::operator()' requested here
      266 |       __ptr_.second()(__tmp);
          |       ^
    external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/__memory/unique_ptr.h:236:71: note: in instantiation of member function 'std::unique_ptr<sorbet::KeyValueStore>::reset' requested here
      236 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX23 ~unique_ptr() { reset(); }
          |                                                                       ^
    main/cache/cache-orig.cc:11:102: note: in instantiation of member function 'std::unique_ptr<sorbet::KeyValueStore>::~unique_ptr' requested here
       11 | unique_ptr<OwnedKeyValueStore> ownIfUnchanged(const core::GlobalState &gs, unique_ptr<KeyValueStore> kvstore) {
          |                                                                                                      ^
    ./main/cache/cache.h:11:7: note: forward declaration of 'sorbet::KeyValueStore'
       11 | class KeyValueStore;
          |       ^
    1 error generated.
    Target //emscripten:sorbet-wasm failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 4.469s, Critical Path: 2.85s
    INFO: 11 processes: 11 internal.
    FAILED: Build did NOT complete successfully

I'm not sure why this is an issue. It could be that this is because
upgrading emscripten is also effectively upgrading us to libc++19, or
maybe there's something else about how `@platforms` work, I'm not sure.

But it seems like we can add this dependency and make it compile so
that's good enough for me.