Make `canModifySymbol` aware of test packages (#10579)
* Add a test that crashes

```
❯ bazel test --config=release-linux-aarch64 --test_output=errors //test:test_LSPTests/testdata/packager/directed-type-member-variance-crash
...
==================== Test output for //test:test_LSPTests/testdata/packager/directed-type-member-variance-crash:
+ exec test/lsp_test_runner --single_test test/testdata/packager/directed-type-member-variance-crash
Pausing
Resuming
[doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
===============================================================================
test/lsp_test_runner.cc:483:
TEST CASE:  LSPTest

test/lsp_test_runner.cc:483: FATAL ERROR: test case CRASHED: SIGSEGV - Segmentation violation signal

===============================================================================
[doctest] test cases:  1 |  0 passed | 1 failed | 0 skipped
[doctest] assertions: 66 | 66 passed | 0 failed |
[doctest] Status: FAILURE!
================================================================================
...
```

```
(lldb) bt 10
* thread #1, name = 'lsp_test_runner', stop reason = signal SIGSEGV: address not mapped to object (fault address=0xaaaaad7f9000)
  * frame #0: 0x0000aaaaab3e04ac lsp_test_runner`operator== at TypePtr.h:225:16 [inlined]
    frame #1: 0x0000aaaaab3e04ac lsp_test_runner`operator= at TypePtr.h:184:19 [inlined]
    frame #2: 0x0000aaaaab3e04ac lsp_test_runner`__move_impl<std::__1::_ClassicAlgPolicy, sorbet::core::TypePtr *, sorbet::core::TypePtr *, sorbet::core::TypePtr *> at move.h:34:15 [inlined]
    frame #3: 0x0000aaaaab3e0498 lsp_test_runner`__move<std::__1::_ClassicAlgPolicy, sorbet::core::TypePtr *, sorbet::core::TypePtr *, sorbet::core::TypePtr *> at move.h:97:16 [inlined]
    frame #4: 0x0000aaaaab3e0498 lsp_test_runner`move<sorbet::core::TypePtr *, sorbet::core::TypePtr *> at move.h:114:10 [inlined]
    frame #5: 0x0000aaaaab3e0498 lsp_test_runner`erase at vector:1662:29 [inlined]
    frame #6: 0x0000aaaaab3e047c lsp_test_runner`::show() at printing.cc:493:24
    frame #7: 0x0000aaaaab11c43c lsp_test_runner`show at Types.h:955:16 [inlined]
    frame #8: 0x0000aaaaab11c42c lsp_test_runner`::validate() at variance.cc:86:81
    frame #9: 0x0000aaaaab11b674 lsp_test_runner`validatePolarity at variance.cc:206:26 [inlined]
```

* Add an analogous test with `include`

* Add an ENFORCE that would catch the bug

    ❯ stog //test:test_LSPTests/testdata/packager/directed-type-member-variance-crash
    INFO: Invocation ID: d022a5b6-ebfc-4f58-b745-808e5e2c262d
    INFO: Analyzed target //test:test_LSPTests/testdata/packager/directed-type-member-variance-crash (1 packages loaded, 12 targets configured).
    FAIL: //test:test_LSPTests/testdata/packager/directed-type-member-variance-crash (see /pay/cache/.cache/bazel/_bazel_jez/d20d72b1ca32c441487bd2cd86bc6db0/execroot/com_stripe_ruby_typer/bazel-out/aarch64-dbg/testlogs/test/test_LSPTests/testdata/packager/directed-type-member-variance-crash/test.log)
    INFO: From Testing //test:test_LSPTests/testdata/packager/directed-type-member-variance-crash:
    ==================== Test output for //test:test_LSPTests/testdata/packager/directed-type-member-variance-crash:
    + exec test/lsp_test_runner --single_test test/testdata/packager/directed-type-member-variance-crash
    Pausing
    Resuming
    [doctest] doctest version is "2.4.9"
    [doctest] run with "--help" for options
    [2026-08-19 22:54:41.687] [fatalFallback] [error] Exception::raise() msg="core/GlobalState.cc:1272 enforced condition !owner.exists() || owner.id() >= boundary.classAndModulesOffset has failed: Entering type member `Elem2` at Loc {file=test/testdata/packager/directed-type-member-variance-crash/parent/test/reopen.rb start=7:3 end=7:22} into `Parent::MyGeneric`, which belongs to an earlier stratum: owner_id=3787 first_incomplete_stratum=2 class_boundary=3794"

    [2026-08-19 22:54:41.812] [fatalFallback] [error] Backtrace:
      #3 0xb07e53cc62bc sorbet::core::GlobalState::enterTypeMember()
      #4 0xb07e53766228 sorbet::namer::(anonymous namespace)::SymbolDefiner::insertTypeMember()
      #5 0xb07e53759960 sorbet::namer::(anonymous namespace)::SymbolDefiner::enterNewDefinitions()
      #6 0xb07e537507d4 sorbet::namer::(anonymous namespace)::defineSymbols()
      #7 0xb07e5374fe84 sorbet::namer::Namer::runInternal()
      #8 0xb07e53750994 sorbet::namer::Namer::run()
      #9 0xb07e535ae464 sorbet::realmain::pipeline::name()

* Make `canModifySymbol` aware of test packages

Fixes the crash. Looks better ignoring whitespace.

`canModifySymbol` attempts to prevent bad mutations to `GlobalState`
such that copying a prefix of the symbol table would not copy the right
data. The logic implicily assumed that mutations created while
processing the test files in a package were safe because we're modifying
the "same" package.

* Convert back to an ENFORCE

* Apply suggestion from @jez