Remove invalid imports from prelude packages (#10701)
* Add master exp test

Shows the behavior of the non-package-directed mode on master, because I
plan to add an autocorrect in a bit for this while I'm here.

* Add failing test

    + exec test/pipeline_test_runner --single_test test/testdata/packager/directed-prelude-import
    [doctest] doctest version is "2.4.9"
    [doctest] run with "--help" for options
    [2026-09-28 22:49:43.756] [fatalFallback] [error] Exception::raise() msg="core/packages/Condensation.cc:100 enforced condition remaining > 0 has failed: (no message provided)"

    [2026-09-28 22:49:43.794] [fatalFallback] [error] Backtrace:
      #3 0xca8bc1ad6610 absl::lts_20240722::Span<>::Span<>()
      #4 0xca8bc282f9e4 sorbet::core::packages::(anonymous namespace)::TraversalBuilder::recordStratum<>()
      #5 0xca8bc282f0ac sorbet::core::packages::Condensation::computeTraversal()
      #6 0xca8bc2044400 sorbet::realmain::pipeline::computePackageStrata()
      #7 0xca8bc1a8e820 sorbet::test::DOCTEST_ANON_FUNC_10()
      #8 0xca8bc2a7e454 doctest::Context::run()
      #9 0xca8bc1a91e34 main
      #10 0xe3a855b584c4
      #11 0xe3a855b58598 __libc_start_main
      #12 0xca8bc1a89f70 _start

===============================================================================
test/pipeline_test_runner.cc:526:
TEST CASE:  PerPhaseTest

test/pipeline_test_runner.cc:526: ERROR: test case THREW exception: core/packages/Condensation.cc:100 enforced condition remaining > 0 has failed: (no message provided)

===============================================================================

* Remove invalid imports from prelude packages

* clang-format

* Autocorrect invalid prelude imports

While I was here, I figured I'd add an autocorrect for this case.

* Disable directed prelude import LSP test