Ignore this test
Prism thinks this is a method `def ensure` with an empty body.

Sorbet thinks this is a method `def <method-def-name-missing>` with a
body containing `<ErrorNode>`.

    test/pipeline_test_runner.cc:321: ERROR: Prism desugared tree does not match legacy desugared tree
    @@ -12,7 +12,7 @@
         MethodDef{
           loc = 2:3-6:1
           flags = {}
    -      name = <U <method-def-name-missing>><<U <todo method>>>
    +      name = <U ensure><<U <todo method>>>
           args = [BlockParam{ loc = , expr = UnresolvedIdent{
               loc =
               kind = Local
    @@ -19,13 +19,10 @@
               name = <U <blk>>
             } }]
    -      rhs = Rescue{
    -        loc = 5:3-5:9
    -        body = EmptyTree
    -        rescueCases = [
    -        ]
    -        else = EmptyTree
    -        ensure = EmptyTree
    +      rhs = ConstantLit{
    +        loc = 182-205
    +        symbol = (static-field ::<ErrorNode>)
    +        orig = nullptr
           }
         }
       ]
     }