Add failing tests
This broke on afdf2e6436 (#10705), when moving package modifier parsing
in to namer.

Here's an example failure:

    ==================== Test output for //test:test_PosTests/testdata/packager/directed-duplicate_package_export_all:
    + exec test/pipeline_test_runner --single_test test/testdata/packager/directed-duplicate_package_export_all
    [doctest] doctest version is "2.4.9"
    [doctest] run with "--help" for options
    [2026-10-02 00:18:19.861] [fatalFallback] [error] Exception::raise() msg="namer/namer.cc:86 enforced condition packageName.exists() && packageName.owner == ctx.owner.asClassOrModuleRef() has failed: (no message provided)"

    [2026-10-02 00:18:19.912] [fatalFallback] [error] Backtrace:
      #3 0xbf1a66ae6d64 absl::lts_20240722::Span<>::Span<>()
      #4 0xbf1a6724469c sorbet::namer::(anonymous namespace)::packageInfoForContext()
      #5 0xbf1a67241068 sorbet::namer::(anonymous namespace)::SymbolDefiner::modifyClass()
      #6 0xbf1a67232f94 sorbet::namer::(anonymous namespace)::SymbolDefiner::enterNewDefinitions()
      #7 0xbf1a67228b38 sorbet::namer::(anonymous namespace)::defineSymbols()
      #8 0xbf1a67228180 sorbet::namer::Namer::runInternal()
      #9 0xbf1a67228d00 sorbet::namer::Namer::run()
      #10 0xbf1a66a9c950 sorbet::test::name()
      #11 0xbf1a66a9ee8c sorbet::test::DOCTEST_ANON_FUNC_10()
      #12 0xbf1a67a9059c doctest::Context::run()
      #13 0xbf1a66aa2588 main
      #14 0xe360f8d584c4
      #15 0xe360f8d58598 __libc_start_main
      #16 0xbf1a66a9a6b0 _start

    ===============================================================================
    test/pipeline_test_runner.cc:526:
    TEST CASE:  PerPhaseTest

    test/pipeline_test_runner.cc:526: ERROR: test case THREW exception: namer/namer.cc:86 enforced condition packageName.exists() && packageName.owner == ctx.owner.asClassOrModuleRef() has failed: (no message provided)

    ===============================================================================
    [doctest] test cases:  1 |  0 passed | 1 failed | 0 skipped
    [doctest] assertions: 22 | 22 passed | 0 failed |
    [doctest] Status: FAILURE!