Error: class/module "defined" in different files (#1444)
* Create ErrorClass

* Factor out definesBehavior

* Get basic error working

* Exclude root

* move to post-classdef

* Exclude synthesized

* fix error number

* --stripe-mode + cleanup

* TODO

* fix tests

* use const uniqptr, move defines to be private

* vector<parsedfile> for namer

* remove single file namer

* fix in a test

* Move to BehaviorHelpers and rename

* Fix test_corpus

* missed a test

* Also suppress in lsp

* Better NameInserter scope tracking

* move error flush after Namer::run

* Update ast/Helpers.h

Co-Authored-By: Dmitry Petrashko <dmitry@stripe.com>