Squashed commit of the following:
commit 418869b43a2ff8c51b343af270b82728eaa7a29e
Author: Neil Parikh <parikh.neil@me.com>
Date:   Fri Sep 19 15:49:38 2025 -0400

    test changes

commit 6cfb3ab86ddcf96efe5cda6ad3e5c215fd0c901b
Author: Douglas Eichelberger <doug.eichelberger@gusto.com>
Date:   Fri Aug 22 11:15:15 2025 -0700

    Fix remaining tests

commit 3e26a6412b06e2a9473e3302e0a6ec2cec0b318f
Author: Douglas Eichelberger <doug.eichelberger@gusto.com>
Date:   Fri Aug 22 11:03:59 2025 -0700

    Update test.out

commit 0ed21debf94a898769ff8a911b4f0c5f48d20fb6
Author: Douglas Eichelberger <697964+dduugg@users.noreply.github.com>
Date:   Sat Aug 16 12:41:20 2025 -0700

    Fix puts / p param types

    ```
    [1] pry(main)> puts BasicObject.new
    NoMethodError: undefined method `to_s' for an instance of BasicObject (NoMethodError)
    from (pry):1:in `puts'
    [2] pry(main)> puts Object.new
    #<Object:0x000000011f83a458>
    => nil
    [3] pry(main)> p BasicObject.new
    NoMethodError: undefined method `inspect' for an instance of BasicObject (NoMethodError)
    from (pry):3:in `p'
    [4] pry(main)> p Object.new
    #<Object:0x000000011e33ad78>
    => #<Object:0x000000011e33ad78>
    ```