Fix packager import SCC ID crash differently (#9204)
* Add failing test

    ❯ stog //test:test_PosTests/testdata/packager/dag
    INFO: Invocation ID: 7eec42f5-9a0f-46d3-9350-73a493cb437e
    INFO: Analyzed target //test:test_PosTests/testdata/packager/dag (139 packages loaded, 4049 targets configured).
    INFO: Found 1 test target...
    FAIL: //test:test_PosTests/testdata/packager/dag (see /private/var/tmp/_bazel_jez/491a13d243378e23690a7f8390a5c09f/execroot/com_stripe_ruby_typer/bazel-out/darwin_arm64-dbg/testlogs/test/test_PosTests/testdata/packager/dag/test.log)
    INFO: From Testing //test:test_PosTests/testdata/packager/dag:
    ==================== Test output for //test:test_PosTests/testdata/packager/dag:
    + exec test/pipeline_test_runner --single_test=test/testdata/packager/dag
    [doctest] doctest version is "2.4.9"
    [doctest] run with "--help" for options
    [2025-08-21 04:02:18.275] [fatalFallback] [error] Exception::raise() msg="packager/packager.cc:1402 enforced condition packageDB.getPackageInfo(packageName).exists() has failed: (no message provided)"

    [2025-08-21 04:02:18.806] [fatalFallback] [error] Backtrace:
    sorbet::test::DOCTEST_ANON_FUNC_10() (in pipeline_test_runner) + 0
    sorbet::packager::(anonymous namespace)::PackageDBPackageGraph::getSCCId(sorbet::core::packages::MangledName) const (in pipeline_test_runner) + 188
    void sorbet::packager::ComputePackageSCCs::strongConnect<(sorbet::core::packages::ImportType)0, sorbet::packager::(anonymous namespace)::PackageDBPackageGraph>(sorbet::core::packages::MangledName, sorbet::packager::ComputePackageSCCs::NodeInfo&, sorbet::packager::(anonymous namespace)::PackageDBPackageGraph&) (in pipeline_test_runner) + 1028
    void sorbet::packager::ComputePackageSCCs::tarjan<(sorbet::core::packages::ImportType)0, sorbet::packager::(anonymous namespace)::PackageDBPackageGraph>(sorbet::packager::(anonymous namespace)::PackageDBPackageGraph&) (in pipeline_test_runner) + 360
    sorbet::core::packages::Condensation sorbet::packager::ComputePackageSCCs::run<sorbet::packager::(anonymous namespace)::PackageDBPackageGraph>(sorbet::core::GlobalState&, sorbet::packager::(anonymous namespace)::PackageDBPackageGraph&) (in pipeline_test_runner) + 132
    void sorbet::packager::(anonymous namespace)::packageRunCore<(sorbet::packager::(anonymous namespace)::PackagerMode)2>(sorbet::core::GlobalState&, sorbet::WorkerPool&, absl::lts_20240722::Span<sorbet::ast::ParsedFile>) (in pipeline_test_runner) + 416
    sorbet::packager::Packager::run(sorbet::core::GlobalState&, sorbet::WorkerPool&, absl::lts_20240722::Span<sorbet::ast::ParsedFile>) (in pipeline_test_runner) + 56
    sorbet::test::package(sorbet::core::GlobalState&, std::__1::unique_ptr<sorbet::WorkerPool, std::__1::default_delete<sorbet::WorkerPool>>&, absl::lts_20240722::Span<sorbet::ast::ParsedFile>, sorbet::test::ExpectationHandler&, std::__1::vector<std::__1::shared_ptr<sorbet::test::RangeAssertion>, std::__1::allocator<std::__1::shared_ptr<sorbet::test::RangeAssertion>>>&) (in pipeline_test_runner) + 144
    sorbet::test::DOCTEST_ANON_FUNC_10() (in pipeline_test_runner) + 3256
    doctest::Context::run() (in pipeline_test_runner) + 4388
    main (in pipeline_test_runner) + 1872
    start (in dyld) + 6076

    ===============================================================================
    test/pipeline_test_runner.cc:348:
    TEST CASE:  PerPhaseTest

    test/pipeline_test_runner.cc:348: ERROR: test case THREW exception: packager/packager.cc:1402 enforced condition packageDB.getPackageInfo(packageName).exists() has failed: (no message provided)

    ===============================================================================
    [doctest] test cases:  1 |  0 passed | 1 failed | 0 skipped
    [doctest] assertions: 14 | 14 passed | 0 failed |
    [doctest] Status: FAILURE!
    external/bazel_tools/tools/test/test-setup.sh: line 353: 73612 Killed: 9               sleep 10
    ================================================================================
    Target //test:test_PosTests/testdata/packager/dag up-to-date:
      bazel-bin/test/test_PosTests/testdata/packager/dag
    INFO: Elapsed time: 17.830s, Critical Path: 12.17s
    INFO: 23 processes: 4 disk cache hit, 7 internal, 12 local.
    INFO: Build completed, 1 test FAILED, 23 total actions
    //test:test_PosTests/testdata/packager/dag                               FAILED in 2.3s
      /private/var/tmp/_bazel_jez/491a13d243378e23690a7f8390a5c09f/execroot/com_stripe_ruby_typer/bazel-out/darwin_arm64-dbg/testlogs/test/test_PosTests/testdata/packager/dag/test.log

    Executed 1 out of 1 test: 1 fails locally.

* Revert "Verify that package info exists when handling imports (#9202)"

This reverts commit 64b9e3999718d6256fad11143a5e31c764ff36f7.

* Fix by establishing invariant

Rather than treating the symptoms.

* Show how it fails now

* Update packager/packager.cc

Co-authored-by: Trevor Elliott <awesomelyawesome@gmail.com>

---------

Co-authored-by: Trevor Elliott <awesomelyawesome@gmail.com>