Switch to using `--incompatible_enable_cc_toolchain_resolution` (#7912)
* Update abseil-cpp to version 20240116.2

* Some things in absl got different names

* tools/scripts/format_cxx.sh

* Somehow ClassOrModule gets smaller?

It looks like absl made some changes to UnorderedMap which shaves off 8
bytes from `core::ClassOrModule`. It looks like that's because
UnorderedMap gets 8 bytes smaller. Somehow, it seems that this is the
only class inside Sorbet that we have a `CheckSize` annotation on that
uses `UnorderedMap`:

    ❯ rg -l -t h 'UnorderedMap' | xargs rg -l CheckSize | xargs rg -n UnorderedMap
    common/common.h
    24:template <class K, class V> using UnorderedMap = absl::flat_hash_map<K, V>;

    core/Types.h
    235:using IntrinsicMethodsDispatchMap = UnorderedMap<NameRef, const std::vector<NameRef>>;

    core/Symbols.h
    605:    UnorderedMap<NameRef, SymbolRef> members_;
    607:    UnorderedMap<NameRef, SymbolRef> &members() {
    610:    const UnorderedMap<NameRef, SymbolRef> &members() const {

    core/GlobalState.h
    338:    UnorderedMap<std::string, FileRef> fileRefByPath;

(`GlobalState.h` has a CheckSize but it's commented out, actually.)

So `UnorderedMap` gets smaller by 8 bytes and this `core::ClassOrModule`
benefits.

I tried to find the commit in abseil-cpp that introduced that change,
but couldn't find it after a few minutes of searching. In any case, a
welcome change.

* Remove a TODO about `-Wdeprecated-builtins`

* prework: Fix unused-but-set-variable warnings

* Use the new emsdk toolchain

* Add patch to workaround Apple Silicon macOS build

The emsdk library uses a Python script to attempt to infer some
information about which `node` binary to try to run. That script runs on
the host directly, and uses `platform.machine()` to get the
architecture.

But earlier in the pipeline, the Bazel config uses information from
Bazel to figure out which nodejs external repository to fetch and
unpack (not Python).

Until we stop doing this weird Rosetta Bazel dance, we need to forcibly
have emscripten choose the version that the emsdk Bazel toolchain will
have fetched.

This also means that we won't be able to build our WebAssembly build on
x86_64 versions of macOS, but we don't do that during development nor in
CI (it still works to create WebAssembly builds on Apple Silicon macOS
and on Linux), but that restriction should be lifted once we can switch
away from running Bazel under Rosetta and drop this patch.

* Replace Pointer_stringify with UTF8ToString

* Use @platforms instead of our custom config

* Fix issue with forward declares/incomplete types in cache

This is the issue I was seeing:

      (cd /private/var/tmp/_bazel/491a13d243378e23690a7f8390a5c09f/sandbox/darwin-sandbox/590/execroot/com_stripe_ruby_typer && \
      exec env - \
        EMCC_WASM_BACKEND=1 \
        EM_BIN_PATH=external/emscripten_bin_mac \
        EM_CONFIG_PATH=external/emsdk/emscripten_toolchain/emscripten_config \
        PATH=/bin:/usr/bin:/usr/local/bin \
        PWD=/proc/self/cwd \
        TMPDIR=/var/folders/tv/zxkj31vd52n40j8fyt91vtj40000gn/T/ \
      /usr/bin/sandbox-exec -f /private/var/tmp/_bazel/491a13d243378e23690a7f8390a5c09f/sandbox/darwin-sandbox/590/sandbox.sb /private/var/tmp/_bazel/install/22a33b4bcd3e158cee3fae2c530b47de/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel/491a13d243378e23690a7f8390a5c09f/sandbox/darwin-sandbox/590/stats.out' external/emsdk/emscripten_toolchain/emcc.sh @bazel-out/wasm-fastbuild-ST-b4dbd4a2bfc4/bin/main/cache/_objs/cache/cache-orig.o.params)
    In file included from main/cache/cache-orig.cc:1:
    In file included from ./main/cache/cache.h:4:
    In file included from external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/memory:939:
    In file included from external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/__memory/shared_ptr.h:33:
    external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/__memory/unique_ptr.h:64:19: error: invalid application of 'sizeof' to an incomplete type 'sorbet::KeyValueStore'
       64 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
          |                   ^~~~~~~~~~~
    external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/__memory/unique_ptr.h:266:7: note: in instantiation of member function 'std::default_delete<sorbet::KeyValueStore>::operator()' requested here
      266 |       __ptr_.second()(__tmp);
          |       ^
    external/emscripten_bin_mac/emscripten/cache/sysroot/include/c++/v1/__memory/unique_ptr.h:236:71: note: in instantiation of member function 'std::unique_ptr<sorbet::KeyValueStore>::reset' requested here
      236 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_SINCE_CXX23 ~unique_ptr() { reset(); }
          |                                                                       ^
    main/cache/cache-orig.cc:11:102: note: in instantiation of member function 'std::unique_ptr<sorbet::KeyValueStore>::~unique_ptr' requested here
       11 | unique_ptr<OwnedKeyValueStore> ownIfUnchanged(const core::GlobalState &gs, unique_ptr<KeyValueStore> kvstore) {
          |                                                                                                      ^
    ./main/cache/cache.h:11:7: note: forward declaration of 'sorbet::KeyValueStore'
       11 | class KeyValueStore;
          |       ^
    1 error generated.
    Target //emscripten:sorbet-wasm failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 4.469s, Critical Path: 2.85s
    INFO: 11 processes: 11 internal.
    FAILED: Build did NOT complete successfully

I'm not sure why this is an issue. It could be that this is because
upgrading emscripten is also effectively upgrading us to libc++19, or
maybe there's something else about how `@platforms` work, I'm not sure.

But it seems like we can add this dependency and make it compile so
that's good enough for me.

* Rename target for consistency

* tools/scripts/format_build_files.sh

* Fix compilation DB

* We don't build a tarfile anymore

* Delete old stuff

* Assign a TODO to me

* Switch to mainline bazel-contrib/toolchains_llvm

Includes a number of patches, originally made against the
`jez-more-tools` branch of our fork. You can see the full list of
commits here:

<https://github.com/bazel-contrib/toolchains_llvm/compare/0.10.3...sorbet:bazel-toolchain:8d9165fd3560f6ff50bc4794972f714f4ba2adaa>

The commits themselves are here:

- **Add clangd and llvm-symbolizer as aliased tools** (f16a6b0)

- **Apply changes from sorbet/bazel-toolchain#7** (9db8ae1)

  Nathan's changes were made against a version of bazel-toolchain that
  used the old toolchain configuration mechanism.

  This makes the same changes against upstream.

- **Add another URL** (6589ec9)

  We have custom release builds of LLVM, so that 15.0.7 is available on
  all the platforms we support. This commit adds the first of those
  release tarball's checksums.

- **Add another URL** (a5a404f)

  This commit adds the second of those release tarball's checksums.

- **Teach release_name.bzl about our builds** (9b43d0c)

  One last commit to make the toolchain aware of our custom 15.0.7
  builds. This one teaches it about which ubuntu version these builds
  were built against.

- **New attribute extra_compiler_files (#245)** (1da01e6)

  I cherry-picked this commit in order to make it easier to cherry-pick
  the commit that follows. It should be a benign change that doesn't
  affect us, but makes it easier to cherry-pick the following change
  without needing to resolve tons of merge conflicts. The original
  commit message is as follows:

  ---------

  This helps inject files into the compiler action sandbox. The files can
  then be used in the compiler command line, e.g. the sanitizer ignore
  list.

  ---------

  Co-authored-by: Siddhartha Bagaria <starsid@gmail.com>

- **Use LLD linker for Darwin** (c83804a)

  Originally from this commit:

  <https://github.com/bazel-contrib/toolchains_llvm/pull/286/commits/8179a799053e56f312afda027afe6ac59ad2ab31>

  The PR that this change landed in ended up making a followup commit to
  make the change optional, so that people could opt into it by passing
  `--linkopt` and/or `--host_linkopt` to set something like

      --linkopt=-fuse-ld=ld64.lld

  We're seeing behavior where if we **ever** use the system linker, it
  fails to link (because it attempts to link libunwind at the wrong
  location), so we need to make this linker be used all the time. There is
  no way to opt out of using `ld64.lld` with this commit.

- **Fix "Use LLD linker for Darwin" to work with `absolute_paths = True`** (8d9165f)

  The previous commit has one bug, in that it doesn't work with absolute
  paths. This fix should be enough to fix that, and we should likely
  contribute this upstream, but I haven't gotten around to doing that
  yet.

* Fix assorted LLVM tools