Remove generic param from Vector/Matrix RBI
This removes the generic macros from the vendored RBIs for `Matrix` and
its collaborating class `Vector`. Using the current RBI file the
`Matrix` class is not usable in a signature at any `typed:` level
(including `false`).

Any reference to the class as a type, for example `sig { params(x:
Matrix).void }`, fails static typechecks with:

    5045: Malformed type declaration. Generic class without type arguments `Matrix`

This cannot be fixed by using e.g. `Matrix[Integer]` because it will
blow up at runtime since `Matrix.[]` exists and checks its arguments.
`srb tc -a` will autocorrect to `Matrix[T.untyped]` which also fails at
runtime unless runtime checking is disabled. The runtime error looks
like the following:

    lib/ruby/gems/3.1.0/gems/matrix-0.4.2/lib/matrix.rb:1756:in `convert_to_array': undefined method `to_ary' for #<T::Types::Untyped:0x000000010ada39e0> (NoMethodError)

      converted = obj.to_ary
                     ^^^^^^^
    from lib/ruby/gems/3.1.0/gems/matrix-0.4.2/lib/matrix.rb:93:in `block in rows'
    from lib/ruby/gems/3.1.0/gems/matrix-0.4.2/lib/matrix.rb:92:in `map!'
    from lib/ruby/gems/3.1.0/gems/matrix-0.4.2/lib/matrix.rb:92:in `rows'
    from lib/ruby/gems/3.1.0/gems/matrix-0.4.2/lib/matrix.rb:79:in `[]'
    from repro.rb:9:in `block in <class:Foo>'
    from lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10565/lib/types/private/methods/_methods.rb:351:in `instance_exec'
    from lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10565/lib/types/private/methods/_methods.rb:351:in `run_builder'
    from lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10565/lib/types/private/methods/_methods.rb:331:in `run_sig'
    from lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10565/lib/types/private/methods/_methods.rb:241:in `block in _on_method_added'
    from lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10565/lib/types/private/methods/_methods.rb:440:in `run_sig_block_for_key'
    from lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10565/lib/types/private/methods/_methods.rb:420:in `maybe_run_sig_block_for_key'
    from lib/ruby/gems/3.1.0/gems/sorbet-runtime-0.5.10565/lib/types/private/methods/_methods.rb:251:in `block in _on_method_added'

It's no great loss to lose the generics here since the RBI doesn't use
them in any meaningful way. At any rate, the Matrix class is not a
general purpose multidimensional array, it's specifically intended to be
used with numeric members.

The `matrix` stdlib class (moved to [standard gem](https://github.com/ruby/matrix) in 3.1) is not usable with sorbet because of a malformed RBI vendored in sorbet.

I've added a testcase that fails before this change.