Fix nested constants
This more closely matches the runtime. If we're going to move the whole
class definition, we don't need to move the individual constants defined
inside that class definition, because doing so will effectively hoist
the constant definition outside of the class definition.

See for example:

    ❯ ruby -r 'minitest/autorun' test/testdata/rewriter/minitest_nested_class.rb
    Run options: --seed 54972

    # Running:

    E

    Finished in 0.000495s, 2020.2028 runs/s, 0.0000 assertions/s.

      1) Error:
    bar#test_0001_foo:
    NameError: uninitialized constant X

        p(X) # error: Unable to resolve constant `X`
          ^
        test/testdata/rewriter/minitest_nested_class.rb:8:in `block (2 levels) in <main>'

    1 runs, 0 assertions, 0 failures, 1 errors, 0 skips