Mark CFGBuilder as entirely `const` (#9764)
* wip: Try to make builder_walk use const tree

* Deal with template specialization error

Without this, we'd get this error:

    ./core/Types.h:59:5: error: static assertion failed due to requirement '!TypePtr::TypeToIsInlined<sorbet::core::NamedLiteralType>::value': Inlined types must specialize `make_type` for each combination of argument types; is one specialization missing?
        static_assert(!TypePtr::TypeToIsInlined<T>::value, "Inlined types must specialize `make_type` for each combination "
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cfg/builder/builder_walk.cc:1119:46: note: in instantiation of function template specialization 'sorbet::core::make_type<sorbet::core::NamedLiteralType, sorbet::core::ClassOrModuleRef, const sorbet::core::NameRef &>' requested here
                        make_insn<Literal>(core::make_type<core::NamedLiteralType>(core::Symbols::Symbol(), rmd.name)));

It might be nice if we could figure out a way to say "anything trivially
copyable to `NameRef`" so that we don't need these three overloads
(`NameRef`, `NameRef &`, `const NameRef &`), but I'm not immediately
sure how to do that.

* Mark it const all the way up to the CFGCollectorAndTyper