Squashed commit of the following:
commit b4d2e966a8efa13816d8fdc787d56647ec34dca4
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Thu Jun 25 18:15:43 2026 -0700

    Also store the Signature in the closure

    This fixes the `module_function` tests, which is unfortunate.

commit 127c6a81d2cb854d448b6daa214552cf5af01ea0
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Thu Jun 25 18:14:01 2026 -0700

    fixup! Add failing tests

commit 24f2d9b87b76b718440522b1e86a0e7cb035beb3
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Thu Jun 25 18:06:15 2026 -0700

    fixup! Add failing tests

commit fbc7740d3b5d5b920e5931f0bb5f48b5217d2b12
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Thu Jun 25 10:24:49 2026 -0700

    Fix lint

commit d89f13560146ccbff2ebe9e2178e959ee201016f
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Wed Jun 24 20:54:28 2026 -0700

    Make sorbet-runtime tolerant of method redefinitions

commit d102c3ec06a7ab8b686771919823d027e1ed1538
Author: Jake Zimmerman <zimmerman.jake@gmail.com>
Date:   Wed Jun 24 20:50:31 2026 -0700

    Add failing tests

    The failures:

          1) Failure:
        Opus::Types::Test::EdgeCasesTest#test_0026_drops an un-evaluated sig if the method is redefined [test/types/edge_cases.rb:992]:
        Expected #<T::Private::Methods::Signature:0x0000fa10381fb420 @method=#<UnboundMethod: #<Class:0x0000fa1037c02dc0>#foo() /pay/home/jez/sorbet/gems/sorbet-runtime/test/types/edge_cases.rb:986>, @method_name=:foo, @block_type=nil, @block_name=nil, @rest_type=nil, @rest_name=nil, @keyrest_type=nil, @keyrest_name=nil, @return_type=#<T::Types::Simple:0x0000fa1038005dc8 @raw_type=Integer, @name="Integer", @nilable=#<T::Private::Types::SimplePairUnion:0x0000fa1038000be8 @raw_a=Integer, @raw_b=NilClass, @types=[#<T::Types::Simple:0x0000fa1038005dc8 ...>, #<T::Types::Simple:0x0000fa10383569c8 @raw_type=NilClass, @name="NilClass">]>>, @effective_return_type=#<T::Types::Simple:0x0000fa1038005dc8 @raw_type=Integer, @name="Integer", @nilable=#<T::Private::Types::SimplePairUnion:0x0000fa1038000be8 @raw_a=Integer, @raw_b=NilClass, @types=[#<T::Types::Simple:0x0000fa1038005dc8 ...>, #<T::Types::Simple:0x0000fa10383569c8 @raw_type=NilClass, @name="NilClass">]>>, @bind=nil, @mode="standard", @check_level=:always, @parameters=[], @on_failure=nil, @override_allow_incompatible=false, @defined_raw=nil, @arg_types=[], @kwarg_types={}, @req_arg_count=0, @req_kwarg_names=[]> to be nil.

          2) Error:
        Opus::Types::Test::EdgeCasesTest#test_0027_does not validate a captured old method against a new sig:
        TypeError: Return value: Expected type Float, got type Integer with value 0
        Caller: /pay/home/jez/sorbet/gems/sorbet-runtime/test/types/edge_cases.rb:1022
        Definition: /pay/home/jez/sorbet/gems/sorbet-runtime/test/types/edge_cases.rb:1008 (#<Class:0x0000fa1037d36728>.foo)
            lib/types/configuration.rb:293:in `call_validation_error_handler_default'
            lib/types/configuration.rb:300:in `call_validation_error_handler'
            lib/types/private/methods/call_validation.rb:381:in `report_error'
            lib/types/private/methods/call_validation.rb:340:in `validate_call'
            lib/types/private/methods/_methods.rb:379:in `block in _on_method_added'
            test/types/edge_cases.rb:1022:in `call'
            test/types/edge_cases.rb:1022:in `block in <class:EdgeCasesTest>'

          3) Failure:
        Opus::Types::Test::EdgeCasesTest#test_0028_preserves define_method wrapper when sig is evaluated via bind_call [test/types/edge_cases.rb:1045]:
        Expected: "wrapped(original)"
          Actual: "original"