Silence some "aligned allocation" errors
These are the errors that we were seeing before passing this flag:

    ERROR: /private/var/tmp/_bazel/491a13d243378e23690a7f8390a5c09f/external/com_google_protobuf/BUILD:161:11: Compiling src/google/protobuf/arena.cc failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target @@com_google_protobuf//:protobuf_lite) external/llvm_toolchain_15_0_7/bin/cc_wrapper.sh -U_FORTIFY_SOURCE '--target=aarch64-apple-macosx' -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics -Wall -Wthread-safety ... (remaining 50 arguments skipped)
    In file included from external/com_google_protobuf/src/google/protobuf/arena.cc:37:
    external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:160:5: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.13 or newer
        delete static_cast<T*>(value);
        ^
    external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:145:52: note: in instantiation of member function 'google::protobuf::internal::ThreadLocalStorage<google::protobuf::internal::ArenaImpl::ThreadCache>::Delete' requested here
        pthread_key_create(&key_, &ThreadLocalStorage::Delete);
                                                       ^
    external/com_google_protobuf/src/google/protobuf/arena.cc:61:11: note: in instantiation of member function 'google::protobuf::internal::ThreadLocalStorage<google::protobuf::internal::ArenaImpl::ThreadCache>::ThreadLocalStorage' requested here
          new internal::ThreadLocalStorage<ThreadCache>();
              ^
    external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:160:5: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
        delete static_cast<T*>(value);
        ^
    external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:153:16: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.13 or newer
          result = new T();
                   ^
    external/com_google_protobuf/src/google/protobuf/arena.cc:62:26: note: in instantiation of member function 'google::protobuf::internal::ThreadLocalStorage<google::protobuf::internal::ArenaImpl::ThreadCache>::Get' requested here
      return *thread_cache_->Get();
                             ^
    external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:153:16: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
          result = new T();
                   ^
    external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:153:16: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.13 or newer
          result = new T();
                   ^
    external/com_google_protobuf/src/google/protobuf/stubs/mutex.h:153:16: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
    3 errors generated.

It's not clear what's specifying the minimum OS version--it's possible
that we want to figure out a way to pass a larger mimimum OS version,
because 10.13 is macOS High Sierra (7 years out of date at time of
commit).